import { Injectable } from '@nestjs/common';
import { McpToolRegistry } from './mcp-tool';
import { getVedadbPool } from '@orbit/db';

export function registerAllMcpTools(registry: McpToolRegistry) {
  // 1. Search posts in user's network
  registry.register({
    name: 'search_feed',
    description: 'Search posts in the user\'s home feed by text query. Returns top N matches.',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search text' },
        limit: { type: 'number', description: 'Max results', default: 10 },
      },
      required: ['query'],
    },
    async handler(input, ctx) {
      const limit = Math.min(input.limit || 10, 50);
      const result = getVedadbPool().query(
        `SELECT p.post_id as id, p.content_text, p.mode, p.created_at, u.handle, u.display_name
         FROM posts p
         JOIN users u ON u.did = p.author_id
         WHERE p.author_id IN (
           SELECT followee_id FROM follows WHERE follower_id = $1
         ) AND p.search_vector @@ plainto_tsquery('english', $2)
         ORDER BY p.created_at DESC
         LIMIT $3`,
        [ctx.did, input.query, limit],
      );
      return result.rows;
    },
  });

  // 2. Get unread notifications
  registry.register({
    name: 'get_unread_notifications',
    description: 'Get the user\'s unread notifications (mentions, likes, follows, DMs).',
    inputSchema: {
      type: 'object',
      properties: {
        limit: { type: 'number', default: 20 },
      },
      required: [],
    },
    async handler(input, ctx) {
      const limit = Math.min(input.limit || 20, 50);
      const r = getVedadbPool().query(
        `SELECT n.id, n.type, n.payload, n.created_at
         FROM notifications n
         WHERE n.user_id = $1 AND n.read_at IS NULL
         ORDER BY n.created_at DESC
         LIMIT $2`,
        [ctx.did, limit],
      );
      return r.rows;
    },
  });

  // 3. Get recent DM threads
  registry.register({
    name: 'list_dm_threads',
    description: 'List the user\'s recent DM threads (without message content — privacy).',
    inputSchema: {
      type: 'object',
      properties: {
        limit: { type: 'number', default: 10 },
      },
      required: [],
    },
    async handler(input, ctx) {
      const r = getVedadbPool().query(
        `SELECT t.id, t.participants, t.last_message_at, t.thread_type
         FROM threads t
         WHERE $1 = ANY(t.participants)
         ORDER BY t.last_message_at DESC NULLS LAST
         LIMIT $2`,
        [ctx.did, input.limit || 10],
      );
      return r.rows;
    },
  });

  // 4. Suggest people to follow
  registry.register({
    name: 'suggest_follows',
    description: 'Suggest accounts the user might want to follow (people followed by who they follow, minus who they already follow).',
    inputSchema: {
      type: 'object',
      properties: {
        limit: { type: 'number', default: 5 },
      },
      required: [],
    },
    async handler(input, ctx) {
      const r = getVedadbPool().query(
        `WITH second_degree AS (
           SELECT followee_id, COUNT(*) AS shared
           FROM follows
           WHERE follower_id IN (SELECT followee_id FROM follows WHERE follower_id = $1)
             AND followee_id != $1
             AND followee_id NOT IN (SELECT followee_id FROM follows WHERE follower_id = $1)
           GROUP BY followee_id
           ORDER BY shared DESC
           LIMIT $2
         )
         SELECT u.did, u.handle, u.display_name, u.bio, sd.shared
         FROM second_degree sd
         JOIN users u ON u.did = sd.followee_id
         WHERE u.is_active = true`,
        [ctx.did, input.limit || 5],
      );
      return r.rows;
    },
  });

  // 5. Draft a post (does NOT publish — user reviews and confirms)
  registry.register({
    name: 'draft_post',
    description: 'Generate a draft post for the user to review. Does NOT publish.',
    inputSchema: {
      type: 'object',
      properties: {
        topic: { type: 'string', description: 'What to write about' },
        mode: {
          type: 'string',
          enum: ['intimate', 'public', 'visual', 'community'],
          description: 'Which mode (intimate=close friends, public=everyone, visual=image-led, community=group)',
        },
        tone: { type: 'string', enum: ['casual', 'thoughtful', 'funny', 'serious'], default: 'casual' },
      },
      required: ['topic', 'mode'],
    },
    async handler(input) {
      return {
        draft: `[Draft for ${input.mode} mode, ${input.tone || 'casual'} tone]\n\nTopic: ${input.topic}\n\n(Real draft generated by Claude in production.)`,
        mode: input.mode,
        tone: input.tone || 'casual',
        reviewRequired: true,
      };
    },
  });

  // 6. Get usage stats (anti-addiction surface)
  registry.register({
    name: 'get_usage_stats',
    description: 'Get the user\'s usage stats for today/this week (DMs sent, posts made, time on platform).',
    inputSchema: {
      type: 'object',
      properties: {
        period: { type: 'string', enum: ['today', 'week', 'month'], default: 'today' },
      },
      required: [],
    },
    async handler(input, ctx) {
      const since = new Date();
      if (input.period === 'today') since.setHours(0, 0, 0, 0);
      else if (input.period === 'week') since.setDate(since.getDate() - 7);
      else since.setMonth(since.getMonth() - 1);

      const posts = getVedadbPool().query(
        `SELECT COUNT(*) FROM posts WHERE author_id = $1 AND created_at >= $2`,
        [ctx.did, since],
      );
      const dms = getVedadbPool().query(
        `SELECT COUNT(*) FROM messages WHERE sender_did = $1 AND created_at >= $2`,
        [ctx.did, since],
      );
      return {
        period: input.period || 'today',
        postsCreated: parseInt(posts.rows[0].count, 10),
        dmsSent: parseInt(dms.rows[0].count, 10),
      };
    },
  });

  // 7. Export user data (GDPR)
  registry.register({
    name: 'export_my_data',
    description: 'Initiate a GDPR-compliant export of all the user\'s data. Returns a download URL.',
    inputSchema: {
      type: 'object',
      properties: {},
      required: [],
    },
    async handler(input, ctx) {
      getVedadbPool().query(
        `INSERT INTO gdpr_requests (user_did, type, status, created_at)
         VALUES ($1, 'export', 'pending', NOW())`,
        [ctx.did],
      );
      return {
        message: 'Export request queued. You will receive a download link via email within 24 hours.',
        requestType: 'export',
        gdprCompliant: true,
      };
    },
  });

  // 8. Search users by handle or display name
  registry.register({
    name: 'find_user',
    description: 'Search for users by @handle or display name. Returns up to 10 matches.',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search text (handle or name)' },
      },
      required: ['query'],
    },
    async handler(input) {
      const r = getVedadbPool().query(
        `SELECT did, handle, display_name, bio, follower_count
         FROM users
         WHERE handle ILIKE $1 OR display_name ILIKE $1
         ORDER BY follower_count DESC NULLS LAST
         LIMIT 10`,
        [`%${input.query}%`],
      );
      return r.rows;
    },
  });
}
